## 판다스데이터 가공하기

In [3]:
import pandas as pd
import numpy as np

filname = 'dust1.xlsx'
dust = pd.read_excel

In [4]:
import pandas as pd
import numpy as np

filname = 'dust1.xlsx'
dust = pd.read_excel(filname)
dust.head()

,지역,망,측정소코드,측정소명,측정일시,SO2,CO,O3,NO2,PM10,PM25,주소
0,서울 송파구,도시대기,111273,송파구,2021040101,0.004,1.0,0.002,0.066,50,18,서울 송파구 백제고분로 236
1,서울 송파구,도시대기,111273,송파구,2021040102,0.004,0.8,0.002,0.058,48,20,서울 송파구 백제고분로 236
2,서울 송파구,도시대기,111273,송파구,2021040103,0.004,0.8,0.002,0.055,44,20,서울 송파구 백제고분로 236
3,서울 송파구,도시대기,111273,송파구,2021040104,0.003,0.8,0.002,0.055,40,20,서울 송파구 백제고분로 236
4,서울 송파구,도시대기,111273,송파구,2021040105,0.004,0.8,0.002,0.053,38,17,서울 송파구 백제고분로 236

## 컬럼(열, 변수, 피처) 삭제 / 생성

### drop(칼럼명, axis=1) --> 컬럼(열) 삭제

- drop(...., axis=0) --> 행 삭제 ( axis=0은 생략 가능)

In [5]:
# 지역, 망, 측정소코드 삭제

dust.drop(['지역', '망', '측정소코드'], axis=1)

   측정소명        측정일시    SO2   CO     O3    NO2  PM10  PM25                주소
0   송파구  2021040101  0.004  1.0  0.002  0.066    50    18  서울 송파구 백제고분로 236
1   송파구  2021040102  0.004  0.8  0.002  0.058    48    20  서울 송파구 백제고분로 236
2   송파구  2021040103  0.004  0.8  0.002  0.055    44    20  서울 송파구 백제고분로 236
3   송파구  2021040104  0.003  0.8  0.002  0.055    40    20  서울 송파구 백제고분로 236
4   송파구  2021040105  0.004  0.8  0.002  0.053    38    17  서울 송파구 백제고분로 236
5   송파구  2021040106  0.004  0.7  0.002  0.051    38    18  서울 송파구 백제고분로 236
6   송파구  2021040107  0.003  0.7  0.003  0.052    38    17  서울 송파구 백제고분로 236
7   송파구  2021040108  0.004  0.8  0.004  0.057    42    20  서울 송파구 백제고분로 236
8   송파구  2021040109  0.004  0.6  0.014  0.046    45    22  서울 송파구 백제고분로 236
9   송파구  2021040110  0.003  0.4  0.028  0.033    44    16  서울 송파구 백제고분로 236
10  송파구  2021040111  0.003  0.3  0.048  0.014    38    15  서울 송파구 백제고분로 236
11  송파구  2021040112  0.003  0.3  0.053  0.012    39    11  서울 송파구 백제고분로 236
12  송파구  2021040113  0.003  0.3  0.056  0.010    44    13  서울 송파구 백제고분로 236
13  송파구  2021040114  0.003  0.3  0.057  0.011    42    14  서울 송파구 백제고분로 236
14  송파구  2021040115  0.003  0.3  0.057  0.013    44    10  서울 송파구 백제고분로 236
15  송파구  2021040116  0.003  0.3  0.060  0.012    45    11  서울 송파구 백제고분로 236
16  송파구  2021040117  0.003  0.4  0.058  0.015    59    10  서울 송파구 백제고분로 236
17  송파구  2021040118  0.003  0.4  0.052  0.018    68    11  서울 송파구 백제고분로 236
18  송파구  2021040119  0.003  0.4  0.049  0.017    59    10  서울 송파구 백제고분로 236
19  송파구  2021040120  0.003  0.4  0.045  0.019    48     8  서울 송파구 백제고분로 236
20  송파구  2021040121  0.003  0.4  0.047  0.016    44     9  서울 송파구 백제고분로 236
21  송파구  2021040122  0.003  0.4  0.046  0.016    41     9  서울 송파구 백제고분로 236
22  송파구  2021040123  0.003  0.4  0.043  0.017    46    14  서울 송파구 백제고분로 236
23  송파구  2021040124  0.002  0.4  0.047  0.013    46    12  서울 송파구 백제고분로 236
24  송파구  2021040201  0.003  0.3  0.048  0.011    44    15  서울 송파구 백제고분로 236
25  송파구  2021040202  0.003  0.3  0.049  0.010    45    11  서울 송파구 백제고분로 236
26  송파구  2021040203  0.003  0.3  0.051  0.009    47    10  서울 송파구 백제고분로 236
27  송파구  2021040204  0.003  0.3  0.050  0.009    45    11  서울 송파구 백제고분로 236
28  송파구  2021040205  0.002  0.3  0.050  0.010    44    13  서울 송파구 백제고분로 236
29  송파구  2021040206  0.003  0.3  0.044  0.015    42    11  서울 송파구 백제고분로 236
30  송파구  2021040207  0.002  0.4  0.039  0.020    40     9  서울 송파구 백제고분로 236
31  송파구  2021040208  0.003  0.4  0.030  0.031    43    12  서울 송파구 백제고분로 236

In [6]:
dust.head()

,지역,망,측정소코드,측정소명,측정일시,SO2,CO,O3,NO2,PM10,PM25,주소
0,서울 송파구,도시대기,111273,송파구,2021040101,0.004,1.0,0.002,0.066,50,18,서울 송파구 백제고분로 236
1,서울 송파구,도시대기,111273,송파구,2021040102,0.004,0.8,0.002,0.058,48,20,서울 송파구 백제고분로 236
2,서울 송파구,도시대기,111273,송파구,2021040103,0.004,0.8,0.002,0.055,44,20,서울 송파구 백제고분로 236
3,서울 송파구,도시대기,111273,송파구,2021040104,0.003,0.8,0.002,0.055,40,20,서울 송파구 백제고분로 236
4,서울 송파구,도시대기,111273,송파구,2021040105,0.004,0.8,0.002,0.053,38,17,서울 송파구 백제고분로 236

In [7]:
dust = dust.drop(['지역', '망', '측정소코드'], axis=1)

### 컬럼 생성하기(추가)

-데이터프레임명[추가하고 싶은 컬럼명] = 값

In [8]:
dust['ctiy'] = '서울'

In [9]:
dust.head()

,측정소명,측정일시,SO2,CO,O3,NO2,PM10,PM25,주소,ctiy
0,송파구,2021040101,0.004,1.0,0.002,0.066,50,18,서울 송파구 백제고분로 236,서울
1,송파구,2021040102,0.004,0.8,0.002,0.058,48,20,서울 송파구 백제고분로 236,서울
2,송파구,2021040103,0.004,0.8,0.002,0.055,44,20,서울 송파구 백제고분로 236,서울
3,송파구,2021040104,0.003,0.8,0.002,0.055,40,20,서울 송파구 백제고분로 236,서울
4,송파구,2021040105,0.004,0.8,0.002,0.053,38,17,서울 송파구 백제고분로 236,서울

## 컬럼 이름 수정 --> rename()

-데이터프레임명.rename(columns={'기존이름':'새이름})

In [3]:
dust.rename(columns{
    '측정소명':'name',
    '측정일시':'date',
    '주소':'addr'
})
dust.head()

SyntaxError: invalid syntax. Perhaps you forgot a comma? (4070783094.py, line 1)

In [11]:
dust.rename(columns=)

SyntaxError: invalid syntax (3076600711.py, line 1)

name,date가 와야함

### 데이터 형 확인 --> dtypes

In [ ]:
dust.dtypes # 판다스 3버전 부터 object -> str 변경 
#8칸 짜르는

측정소명        str
측정일시      int64
SO2     float64
CO      float64
O3      float64
NO2     float64
PM10      int64
PM25      int64
주소          str
ctiy        str
dtype: object

##데이터 형 변환 -->astype()

- 컬럼명.astype(바꿀 자료형)

In [ ]:
dust['date'].astype(str)

KeyError: 'date'

In [ ]:
dust['date'] = dust['date'].astype(str)

KeyError: 'date'

In [ ]:
dust['date']

KeyError: 'date'

# 첫 8자리만 자른다 --> slice(
    
)

In [ ]:
# 첫 8자리만 자른다 --> slice()
dust['date'] = dust['date'].str,slice(0,8)

KeyError: 'date'

## to_datetime()--> 날짜/시간 형으로 변환 (시계열)

In [ ]:
pd.to_datetime(dust['date'])

KeyError: 'date'

In [ ]:
dust['date'] = pd.to_datetime(dust['date'])
dust.dtypes

KeyError: 'date'